// templates/react/resources/js/pages/auth/register.tsx
import { Link, useForm } from "@inertiajs/react";
import Field from "@/components/field";
import AuthLayout from "@/layouts/auth-layout";
import { route } from "@/routes";

export default function Register() {
  const form = useForm({ name: "", email: "", password: "", password_confirmation: "" });

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    form.post(route("register.store"), { onFinish: () => form.reset("password", "password_confirmation") });
  };

  return (
    <AuthLayout title="Create an account" description="Enter your details below to create your account">
      <form onSubmit={submit} className="flex flex-col gap-4">
        <Field id="name" label="Name" required autoFocus autoComplete="name" placeholder="Full name"
          value={form.data.name} onChange={(e) => form.setData("name", e.target.value)} error={form.errors.name} />
        <Field id="email" label="Email address" type="email" required autoComplete="email" placeholder="email@example.com"
          value={form.data.email} onChange={(e) => form.setData("email", e.target.value)} error={form.errors.email} />
        <Field id="password" label="Password" type="password" required autoComplete="new-password" placeholder="Password"
          value={form.data.password} onChange={(e) => form.setData("password", e.target.value)} error={form.errors.password} />
        <Field id="password_confirmation" label="Confirm password" type="password" required autoComplete="new-password" placeholder="Confirm password"
          value={form.data.password_confirmation} onChange={(e) => form.setData("password_confirmation", e.target.value)} />
        <button type="submit" className="btn btn-primary w-full" disabled={form.processing}>Create account</button>
      </form>
      <p className="text-center text-sm text-base-content/70">
        Already have an account? <Link href={route("login")} className="link">Log in</Link>
      </p>
    </AuthLayout>
  );
}

// templates/svelte/resources/js/pages/auth/register.svelte
<script lang="ts">
  import { route } from "@/routes";
  import { Link, useForm } from "@inertiajs/svelte";
  import Field from "@/components/Field.svelte";
  import AuthLayout from "@/layouts/AuthLayout.svelte";

  const form = useForm({ name: "", email: "", password: "", password_confirmation: "" });

  function submit(event: SubmitEvent) {
    event.preventDefault();
    form.post(route("register.store"), { onFinish: () => form.reset("password", "password_confirmation") });
  }
</script>

<AuthLayout title="Create an account" description="Enter your details below to create your account">
  <form class="flex flex-col gap-4" onsubmit={submit}>
    <Field id="name" bind:value={form.name} label="Name" required autofocus autocomplete="name" placeholder="Full name" error={form.errors.name} />
    <Field id="email" bind:value={form.email} label="Email address" type="email" required autocomplete="email" placeholder="email@example.com" error={form.errors.email} />
    <Field id="password" bind:value={form.password} label="Password" type="password" required autocomplete="new-password" placeholder="Password" error={form.errors.password} />
    <Field id="password_confirmation" bind:value={form.password_confirmation} label="Confirm password" type="password" required autocomplete="new-password" placeholder="Confirm password" />
    <button type="submit" class="btn btn-primary w-full" disabled={form.processing}>Create account</button>
  </form>
  <p class="text-center text-sm text-base-content/70">
    Already have an account? <Link href={route("login")} class="link">Log in</Link>
  </p>
</AuthLayout>
