// apps/my-react/resources/js/pages/auth/reset-password.tsx
import { useForm } from "@inertiajs/react";
import Field from "@/components/field";
import AuthLayout from "@/layouts/auth-layout";
import { route } from "@/routes";

export default function ResetPassword({ token, email }: { token: string; email?: string }) {
  const form = useForm({ token, email: email ?? "", password: "", password_confirmation: "" });

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    form.post(route("password.store"), { onFinish: () => form.reset("password", "password_confirmation") });
  };

  return (
    <AuthLayout title="Reset password" description="Please enter your new password below">
      <form onSubmit={submit} className="flex flex-col gap-4">
        <Field id="email" label="Email" type="email" required autoComplete="email"
          value={form.data.email} onChange={(e) => form.setData("email", e.target.value)} error={form.errors.email} />
        <Field id="password" label="Password" type="password" required autoFocus autoComplete="new-password" placeholder="Password"
          value={form.data.password} onChange={(e) => form.setData("password", e.target.value)} error={form.errors.password} />
        <Field id="password_confirmation" label="Confirm password" type="password" required autoComplete="new-password" placeholder="Confirm password"
          value={form.data.password_confirmation} onChange={(e) => form.setData("password_confirmation", e.target.value)} />
        <button type="submit" className="btn btn-primary w-full" disabled={form.processing}>Reset password</button>
      </form>
    </AuthLayout>
  );
}

// templates/svelte/resources/js/pages/auth/reset-password.svelte
<script lang="ts">
  import { route } from "@/routes";
  import { useForm } from "@inertiajs/svelte";
  import Field from "@/components/Field.svelte";
  import AuthLayout from "@/layouts/AuthLayout.svelte";

  let { token, email }: { token: string; email?: string } = $props();
  const form = useForm({ token, email: email ?? "", password: "", password_confirmation: "" });

  function submit(event: SubmitEvent) {
    event.preventDefault();
    form.post(route("password.store"), { onFinish: () => form.reset("password", "password_confirmation") });
  }
</script>

<AuthLayout title="Reset password" description="Please enter your new password below">
  <form class="flex flex-col gap-4" onsubmit={submit}>
    <Field id="email" bind:value={form.email} label="Email" type="email" required autocomplete="email" error={form.errors.email} />
    <Field id="password" bind:value={form.password} label="Password" type="password" required autofocus autocomplete="new-password" placeholder="Password" error={form.errors.password} />
    <Field id="password_confirmation" bind:value={form.password_confirmation} label="Confirm password" type="password" required autocomplete="new-password" placeholder="Confirm password" />
    <button type="submit" class="btn btn-primary w-full" disabled={form.processing}>Reset password</button>
  </form>
</AuthLayout>
