// apps/my-vue/resources/js/pages/auth/reset-password.vue
<script setup lang="ts">
import { route } from "@/routes";
import { useForm } from "@inertiajs/vue3";
import Field from "@/components/Field.vue";
import AuthLayout from "@/layouts/AuthLayout.vue";

const props = defineProps<{ token: string; email?: string }>();
const form = useForm({ token: props.token, email: props.email ?? "", password: "", password_confirmation: "" });

const submit = () => form.post(route("password.store"), { onFinish: () => form.reset("password", "password_confirmation") });
</script>

<template>
  <AuthLayout title="Reset password" description="Please enter your new password below">
    <form class="flex flex-col gap-4" @submit.prevent="submit">
      <Field id="email" v-model="form.email" label="Email" type="email" required autocomplete="email" :error="form.errors.email" />
      <Field id="password" v-model="form.password" label="Password" type="password" required autofocus autocomplete="new-password" placeholder="Password" :error="form.errors.password" />
      <Field id="password_confirmation" v-model="form.password_confirmation" label="Confirm password" type="password" required autocomplete="new-password" placeholder="Confirm password" />
      <button type="submit" class="btn btn-primary w-full" :disabled="form.processing">Reset password</button>
    </form>
  </AuthLayout>
</template>

// templates/svelte/resources/js/pages/auth/reset-password.svelte
<script lang="ts">
  import { route } from "@/routes";
  import { useForm } from "@inertiajs/svelte";
  import Field from "@/components/Field.svelte";
  import AuthLayout from "@/layouts/AuthLayout.svelte";

  let { token, email }: { token: string; email?: string } = $props();
  const form = useForm({ token, email: email ?? "", password: "", password_confirmation: "" });

  function submit(event: SubmitEvent) {
    event.preventDefault();
    form.post(route("password.store"), { onFinish: () => form.reset("password", "password_confirmation") });
  }
</script>

<AuthLayout title="Reset password" description="Please enter your new password below">
  <form class="flex flex-col gap-4" onsubmit={submit}>
    <Field id="email" bind:value={form.email} label="Email" type="email" required autocomplete="email" error={form.errors.email} />
    <Field id="password" bind:value={form.password} label="Password" type="password" required autofocus autocomplete="new-password" placeholder="Password" error={form.errors.password} />
    <Field id="password_confirmation" bind:value={form.password_confirmation} label="Confirm password" type="password" required autocomplete="new-password" placeholder="Confirm password" />
    <button type="submit" class="btn btn-primary w-full" disabled={form.processing}>Reset password</button>
  </form>
</AuthLayout>
