// templates/react/resources/js/pages/auth/forgot-password.tsx
import { Link, useForm, usePage } from "@inertiajs/react";
import Field from "@/components/field";
import Status from "@/components/status";
import AuthLayout from "@/layouts/auth-layout";
import type { SharedData } from "@/types";
import { route } from "@/routes";

export default function ForgotPassword() {
  const { status } = usePage<SharedData>().props;
  const form = useForm({ email: "" });

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    form.post(route("password.email"));
  };

  return (
    <AuthLayout title="Forgot password" description="Enter your email to receive a password reset link">
      <Status message={status} />
      <form onSubmit={submit} className="flex flex-col gap-4">
        <Field id="email" label="Email address" type="email" required autoFocus placeholder="email@example.com"
          value={form.data.email} onChange={(e) => form.setData("email", e.target.value)} error={form.errors.email} />
        <button type="submit" className="btn btn-primary w-full" disabled={form.processing}>Email password reset link</button>
      </form>
      <p className="text-center text-sm text-base-content/70">
        Or, return to <Link href={route("login")} className="link">log in</Link>
      </p>
    </AuthLayout>
  );
}

// apps/my-svelte/resources/js/pages/auth/forgot-password.svelte
<script lang="ts">
  import { route } from "@/routes";
  import { Link, page, useForm } from "@inertiajs/svelte";
  import Field from "@/components/Field.svelte";
  import Status from "@/components/Status.svelte";
  import AuthLayout from "@/layouts/AuthLayout.svelte";

  const form = useForm({ email: "" });

  function submit(event: SubmitEvent) {
    event.preventDefault();
    form.post(route("password.email"));
  }
</script>

<AuthLayout title="Forgot password" description="Enter your email to receive a password reset link">
  <Status message={page.props.status as string | null} />
  <form class="flex flex-col gap-4" onsubmit={submit}>
    <Field id="email" bind:value={form.email} label="Email address" type="email" required autofocus placeholder="email@example.com" error={form.errors.email} />
    <button type="submit" class="btn btn-primary w-full" disabled={form.processing}>Email password reset link</button>
  </form>
  <p class="text-center text-sm text-base-content/70">
    Or, return to <Link href={route("login")} class="link">log in</Link>
  </p>
</AuthLayout>
