// templates/svelte/resources/js/pages/auth/register.svelte
<script lang="ts">
  import { route } from "@/routes";
  import { Link, useForm } from "@inertiajs/svelte";
  import Field from "@/components/Field.svelte";
  import AuthLayout from "@/layouts/AuthLayout.svelte";

  const form = useForm({ name: "", email: "", password: "", password_confirmation: "" });

  function submit(event: SubmitEvent) {
    event.preventDefault();
    form.post(route("register.store"), { onFinish: () => form.reset("password", "password_confirmation") });
  }
</script>

<AuthLayout title="Create an account" description="Enter your details below to create your account">
  <form class="flex flex-col gap-4" onsubmit={submit}>
    <Field id="name" bind:value={form.name} label="Name" required autofocus autocomplete="name" placeholder="Full name" error={form.errors.name} />
    <Field id="email" bind:value={form.email} label="Email address" type="email" required autocomplete="email" placeholder="email@example.com" error={form.errors.email} />
    <Field id="password" bind:value={form.password} label="Password" type="password" required autocomplete="new-password" placeholder="Password" error={form.errors.password} />
    <Field id="password_confirmation" bind:value={form.password_confirmation} label="Confirm password" type="password" required autocomplete="new-password" placeholder="Confirm password" />
    <button type="submit" class="btn btn-primary w-full" disabled={form.processing}>Create account</button>
  </form>
  <p class="text-center text-sm text-base-content/70">
    Already have an account? <Link href={route("login")} class="link">Log in</Link>
  </p>
</AuthLayout>

// apps/playground/resources/js/Pages/Auth/Register.tsx
import { Form, Link, usePage } from "@inertiajs/react";
import AuthLayout from "../../Layouts/AuthLayout";
import type { RegisterPageProps } from "../../types";

export default function Register() {
  const { flash, errors, csrf } = usePage<RegisterPageProps>().props;

  return (
    <AuthLayout
      title="Create account"
      lede="Spin up a playground user and jump into the dashboard."
    >
      {flash.error ? <div className="flash flash-error">{flash.error}</div> : null}

      <Form action="/register" method="post">
        {({ processing }) => (
          <>
            <input type="hidden" name="_token" value={csrf} />
            <div className="field">
              <label htmlFor="name">Name</label>
              <input id="name" type="text" name="name" autoComplete="name" required />
              {errors.name?.[0] ? (
                <span className="error">{errors.name[0]}</span>
              ) : null}
            </div>
            <div className="field">
              <label htmlFor="email">Email</label>
              <input
                id="email"
                type="email"
                name="email"
                autoComplete="username"
                required
              />
              {errors.email?.[0] ? (
                <span className="error">{errors.email[0]}</span>
              ) : null}
            </div>
            <div className="field">
              <label htmlFor="password">Password</label>
              <input
                id="password"
                type="password"
                name="password"
                autoComplete="new-password"
                required
              />
              {errors.password?.[0] ? (
                <span className="error">{errors.password[0]}</span>
              ) : null}
            </div>
            <button className="btn" type="submit" disabled={processing}>
              {processing ? "Creating…" : "Create account"}
            </button>
          </>
        )}
      </Form>

      <p className="auth-foot">
        Already registered? <Link href="/login">Sign in</Link>
      </p>
    </AuthLayout>
  );
}
