// apps/my-svelte/resources/js/pages/settings/password.svelte
<script lang="ts">
  import { route } from "@/routes";
  import { useForm } from "@inertiajs/svelte";
  import Field from "@/components/Field.svelte";
  import SettingsLayout from "@/layouts/SettingsLayout.svelte";

  const form = useForm({ current_password: "", password: "", password_confirmation: "" });

  function submit(event: SubmitEvent) {
    event.preventDefault();
    form.put(route("password.update"), { preserveScroll: true, onFinish: () => form.reset() });
  }
</script>

<SettingsLayout title="Password settings" heading="Update password" subheading="Ensure your account is using a long, random password to stay secure">
  <form class="flex flex-col gap-4" onsubmit={submit}>
    <Field id="current_password" bind:value={form.current_password} label="Current password" type="password" required autocomplete="current-password" error={form.errors.current_password} />
    <Field id="password" bind:value={form.password} label="New password" type="password" required autocomplete="new-password" error={form.errors.password} />
    <Field id="password_confirmation" bind:value={form.password_confirmation} label="Confirm password" type="password" required autocomplete="new-password" />
    <div class="flex items-center gap-4">
      <button type="submit" class="btn btn-primary" disabled={form.processing}>Save</button>
      {#if form.recentlySuccessful}<span class="text-sm text-success">Saved.</span>{/if}
    </div>
  </form>
</SettingsLayout>

// templates/react/resources/js/pages/settings/password.tsx
import { useForm } from "@inertiajs/react";
import Field from "@/components/field";
import SettingsLayout from "@/layouts/settings-layout";
import { route } from "@/routes";

export default function Password() {
  const form = useForm({ current_password: "", password: "", password_confirmation: "" });

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    form.put(route("password.update"), {
      preserveScroll: true,
      onFinish: () => form.reset(),
    });
  };

  return (
    <SettingsLayout title="Password settings" heading="Update password" subheading="Ensure your account is using a long, random password to stay secure">
      <form onSubmit={submit} className="flex flex-col gap-4">
        <Field id="current_password" label="Current password" type="password" required autoComplete="current-password"
          value={form.data.current_password} onChange={(e) => form.setData("current_password", e.target.value)} error={form.errors.current_password} />
        <Field id="password" label="New password" type="password" required autoComplete="new-password"
          value={form.data.password} onChange={(e) => form.setData("password", e.target.value)} error={form.errors.password} />
        <Field id="password_confirmation" label="Confirm password" type="password" required autoComplete="new-password"
          value={form.data.password_confirmation} onChange={(e) => form.setData("password_confirmation", e.target.value)} />
        <div className="flex items-center gap-4">
          <button type="submit" className="btn btn-primary" disabled={form.processing}>Save</button>
          {form.recentlySuccessful && <span className="text-sm text-success">Saved.</span>}
        </div>
      </form>
    </SettingsLayout>
  );
}
